### ISSUE TITLE
copy ips

### ISSUE THREAD

**Issue by nos3curity** [nos3curity/Raven#12]
need copy buttons next to ip addresses.

also need to be able to export all ips from a team or network.

**Comment by nos3curity** [comment]
added copy to system ip and hostname.

**Comment by soh3ee** [comment]
IP addresses and hostnames have been made copyable on click. A tooltip/pop-up prints "Copied!" upon a successful copy next to the IP address or hostname.


https://github.com/nos3curity/Raven/assets/92657104/9f76c78d-f985-4b1c-8d35-992b6a4a0673
