### ISSUE TITLE
Feature Request: Export of host ips scanned

### ISSUE THREAD

**Issue by 0xtato** [nos3curity/Raven#9]
Functionality to export a list of hosts that were scanned

**Comment by soh3ee** [comment]
Design preview:
<img width="1425" alt="image" src="https://github.com/nos3curity/Raven/assets/92657104/b77af04b-a98a-44b8-bd2c-50d96e473868">

Thoughts on the small icon on the right of each network dropdown header to export a list of all IPs in that network?

Also, is a comma-delimited list the best option? For ex:
10.100.10.1, 10.100.10.2, 10.100.10.3

**Comment by soh3ee** [comment]
Implemented with a newline (`'\n'`) delimited list.

https://github.com/nos3curity/Raven/assets/92657104/dc284910-4069-4e9b-babc-061b3350c9a0
